### ISSUE TITLE
Will you release the other three datasets?

### ISSUE THREAD

**Issue by dengyang17** [AaronHeee/Bundle-MCR#1]
Will you release the other three datasets?

**Comment by AaronHeee** [comment]
Sorry I saw this issue message just now. Sure I am planning to release our datasets of movielens and clothing this week. But for iFashion, I would check whether I can re-distribute it, if not I will only share the processing scripts that you can generate the datasets by yourselves. Please let me know if there are any questions further!

**Comment by AaronHeee** [comment]
Hi @dengyang17, I updated all dataset just now. Please let me know if there are more questions :)
