### ISSUE TITLE
Problem in pull the data

### ISSUE THREAD

**Issue by Snnzhao** [AaronHeee/Bundle-MCR#2]
When try to "git lfs clone", a problem occurs
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/AaronHeee/Bundle-MCR.git/info/lfs'

**Comment by Snnzhao** [comment]
If this is not able to be solved, could you share a google driver linker to the data?

**Comment by Snnzhao** [comment]
This could be solved by folk this project, and change the setting. Then download will contain the full dataset.

**Comment by AaronHeee** [comment]
Thanks, for convenience, I'll provide google gdrive as well (expected to do it this week).

**Comment by AaronHeee** [comment]
Hi @Snnzhao, sorry for the late response. All datasets are uploaded to a google drive now, please check the updated README.md and let me know if you have any questions.
